apiVersion: v1
entries:
  todo-api:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-08-22T09:40:28.6866536+05:30"
    description: A Helm chart for deploy todo application
    digest: 03a54aafcb05f697ea5c919a46eb9f3328bf996959267dbfd7f6006beeeeef63
    name: todo-api
    type: application
    urls:
    - todo-api-0.1.0.tgz
    version: 0.1.0
generated: "2023-08-22T09:40:28.6835923+05:30"
