apiVersion: v2
name: umbrella-chart
description: A Helm chart for to deploy multiple microservices
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: todo-api-h2
    version: 0.1.0
    condition: foo.enabled
    repository: https://padmanabhansaravanan.github.io/Helm/Deploy-h2TodoApi/helm-chart/charts
  - name: todo-api
    version: 0.1.0
    condition: foo.enabled
    repository: https://padmanabhansaravanan.github.io/Helm/DeployTodoApiMySql/todoapp/charts